config/routes.rb
Rails.application.routes.draw do
  resources :events do
    collection do
      get :latest
      post :bulk_delete
      post :bulk_update
    end
    resources :attendees, :controller => 'event_attendees'
    resource :location, :controller => 'event_locations'
  end

  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendee.rb
class Attendee < ApplicationRecord
  belongs_to :event
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :events
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, presence: true

  has_many :attendees
  has_many :event_groupships
  has_many :groups, :through => :event_groupships
  has_one :location
  belongs_to :category

  delegate :name, :to => :category, :prefix => true, :allow_nil => true
  #需修改寫法
  accepts_nested_attributes_for :location, :allow_destroy => true, :reject_if => :all_blank
  #待了解寫法
end

app/models/event_groupship.rb
class EventGroupship < ApplicationRecord
  belongs_to :event
  belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :event_groupships
  has_many :events, :through => :event_groupships
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/event_attendees_controller.rb
class EventAttendeesController < ApplicationController

    before_action :find_event

  def index
    @attendees = @event.attendees
  end

  def show
    @attendee = @event.attendees.find(params[:id])
  end

  def new
    @attendee = @event.attendees.build
  end

  def create
    @attendee = @event.attendees.build(params_attendee)
    if @attendee.save
      redirect_to event_attendees_path, notice: "建立互動者"
    else
      render :new
    end
  end

  def edit
    @attendee = @event.attendees.find(params[:id])
  end

  def update
    @attendee = @event.attendees.build(params[:id])
    if @attendee.update(params_attendee)
      redirect_to event_attendees_path, notice: "更新資料完成"
    else
      render :edit
    end

  end

  def destroy
    @attendee = @event.attendees.find(params[:id])
    @attendee.destroy
    redirect_to event_attendees_path, notice: "刪除資料"
  end

  private
  def params_attendee
    params.require(:attendee).permit(:name)
  end

  def find_event
    @event = Event.find(params[:event_id])
  end
end

app/controllers/event_locations_controller.rb
class EventLocationsController < ApplicationController

  before_action :find_event
  def show
    @location = @event.location
  end

  def new 
    @location = @event.build_location
  end

  def create
    @location = @event.build_location(params_location)
    if @location.save
      redirect_to event_location_url(@event), notice: 新增成功
    else
      render :new
    end
  end

  def edit
    @location = @event.location
  end

  def update
    @location = @event.location
    if @location.update(params_location)
      redirect_to event_location_url(@event), notice: 更新成功
    else
      render :edit
    end
  end

  def destroy
    @location = @event.location
    @location.destroy
    redirect_to event_location_url(@event), notice: 已刪除
  end

  private
  def params_location
    prams.require(:location).permit(:name)
  end

  def find_event
    @event = Event.find(params[:event_id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  before_action :find_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(params_event)
    if @event.save
      redirect_to root_path, notice: "新增成功"
    else
      render :new
    end
  end

  def show
    @page_title = @event.name
  end

  def edit
  end

  def update
    if @event.update(params_event)
      redirect_to root_path, notice: "新增成功"
    else
      render :new
    end
  end

  def destroy
    @event.destroy
    redirect_to root_path, notice: "刪除成功"
  end

  def latest
    @events = Event.order("id DESC").limit(3)
  end

  def bulk_delete
    Event.destroy_all
    redirect_to root_path
  end

  def bulk_update
    ids = Array(params[:ids])
    events = ids.map{ |i| Event.find_by_id(i) }.compact

    if params[:comment] == "Publish"
      events.each{ |e| e.update( :status => "published" ) }
    elsif params[:comment] == "Delete"
      events.each { |e| e.destroy}
    end
    redirect_to root_path
  end

  private
  def find_event
    @event = Event.find(params[:id])
  end

  def params_event
    params.require(:event).permit(:name, :description, :capcity, :category_id, :location_attributes => [:id, :name, :_destroy], :group_ids => [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendees_helper.rb
module EventAttendeesHelper
end

app/helpers/event_locations_helper.rb
module EventLocationsHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def setup_event(event) 
    event.build_location unless event.location
    event
  end
end

app/views/event_attendees/edit.html.erb
<%= form_with(model: [@event, @attendee], url: event_attendee_path(@event, @attendee), method: :patch) do |f| %>
   <%= f.text_field :name %>
   <%= f.submit %>
<% end %>

app/views/event_attendees/index.html.erb
<ul>
  <% @attendees.each do |attendee| %>

    <li><%= attendee.name %></li>
    <li><%= link_to "show", event_attendee_path(@event, attendee) %></li>
    <li><%= link_to "edit", edit_event_attendee_path(@event, attendee) %></li>
    <li><%= link_to "destroy", event_attendee_path(@event, attendee), method: "delete" %></li>

  <% end %>
</ul>

<%= link_to "new", new_event_attendee_path(@event) %>

app/views/event_attendees/new.html.erb
<%= form_with(model: [@event, @attendee], url: event_attendees_path(@event)) do |f| %>
   <%= f.text_field :name %>
   <%= f.submit %>
   
<% end %>

app/views/event_attendees/show.html.erb
<%= @attendee.name %>

app/views/event_locations/edit.html.erb
<%= form_with(model: [@event, @location], url: event_location_path(@event, @location), method: :patch) do |f| %>
   <%= f.text_field :name %>
   <%= f.submit %>
<% end %>

app/views/event_locations/new.html.erb
<%= form_with(model: [@event, @location], url: event_locations_path(@event)) do |f| %>
   <%= f.text_field :name %>
   <%= f.submit %>
<% end %>

app/views/event_locations/show.html.erb
<h1><%= @event.name %></h1>

<% if @event.location %>
  <p><%= @event.location.name %></p>
  <p><%= link_to "edit", edit_event_location_path(@event) %></p>
  <p><%= link_to "destroy", event_location_path(@event), method: "delete" %></p>
<% else %>
  <p>N/A</p>
  <p><%= link_to "新增地點", new_event_location_path(@event) %></p>
<% end %>

app/views/events/_form.html copy.erb
<%= form_for setup_event(@event), :url => event_path(@event), :method => :put do |form| %>

  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :description %>
  <%= form.text_area :description %>

  <%= form.collection_select(:category_id, Category.all, :id, :name) %>

  <%= form.submit %>

  <%= form.fields_for :location do |l_f| %>
    <p>
      <%= l_f.label :name, "地點" %>
      <%= l_f.text_field :name %>

      <% unless l_f.object.new_record? %>
        <%= l_f.label :_destroy, "刪除" %>
        <%= l_f.checkbox :_destroy %>
      <% end %>
    </p>
  <% end %>
<% end %>

app/views/events/_form.html.erb
<%= form_for(@event) do |form| %>

  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :description %>
  <%= form.text_area :description %>

  <%= form.collection_select(:category_id, Category.all, :id, :name) %>

  <%= form.submit %>

  <%= form.fields_for :location do |l_f| %>
    <p>
      <%= l_f.label :name, "地點" %>
      <%= l_f.text_field :name %>

      <% unless l_f.object.new_record? %>
        <%= l_f.label :_destroy, "刪除" %>
        <%= l_f.check_box :_destroy %>
      <% end %>
    </p>
    <% end %>
<% end %>

app/views/events/edit.html.erb
<h1>編輯起來</h1>


<%= form_for setup_event(@event), :url => event_path(@event), :method => :put do |form| %>

  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :description %>
  <%= form.text_area :description %>

  <%= form.collection_select(:category_id, Category.all, :id, :name) %>

  <%= form.submit %>

  <%= form.fields_for :location do |l_f| %>
    <p>
      <%= l_f.label :name, "地點" %>
      <%= l_f.text_field :name %>

      <% unless l_f.object.new_record? %>
        <%= l_f.label :_destroy, "刪除" %>
        <%= l_f.check_box :_destroy %>
      <% end %>
    </p>
  <% end %>
<% end %>

app/views/events/index.html.erb
<h1>主頁</h1>

<%= form_tag bulk_update_events_path do %>
<ul>
  <% @events.each do |event| %>
    <li>
    <%= check_box_tag "ids[]", event.id, false %>
    <%= event.name %>
    <%= link_to "秀出來", event_path(event) %>
    <%= link_to "編輯囉", edit_event_path(event) %>
    <%= link_to "刪除啊", event_path(event), method: :delete, data: {confirm: "要刪除嗎"} %>
    <%= link_to "attendee", event_attendees_path(event) %>
    <%= link_to "location", event_location_path(event) %></li>
  <% end %>
</ul>
  <%= submit_tag "Delete" %>
  <%= submit_tag "Publish" %>
<% end %>

<%= link_to "新增", new_event_path(@event) %>

app/views/events/new.html.erb
<h1>我們來新增</h1>


<%= form_for setup_event(@event), :url => events_path do |form| %>

  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :description %>
  <%= form.text_area :description %>

  <%= form.collection_select(:category_id, Category.all, :id, :name) %>
  <%= form.collection_check_boxes(:group_ids, Group.all, :id, :name) %>

  <%= form.submit %>

  <%= form.fields_for :location do |l_f| %>
    <p>
      <%= l_f.label :name, "地點" %>
      <%= l_f.text_field :name %>

      <% unless l_f.object.new_record? %>
        <%= l_f.label :_destroy, "刪除" %>
        <%= l_f.checkbox :_destroy %>
      <% end %>
    </p>
  <% end %>
<% end %>

app/views/events/show.html.erb
<h1>秀出來啊</h1>

<%= @event.name %>
<p>Category: <%= @event.category.name %></p>
<%= simple_format(@event.description) %>

<p>Group:
  <%= @event.groups.each do |g|%>
    <%= g.name %>
  <% end %>
</p>
<%= link_to "首頁", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title || "Event application" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>